WorldWideTelescope/wwt-webgl-engine

- wwtlib/Util.cs
Not even tested for whether it can compile, at the moment ...
> New URL proxy logic

- wwtlib/Layers/SpreadSheetLayer.cs
- wwtlib/URLHelpers.cs
- wwtlib/Util.cs
- wwtlib/WWTControl.cs
- wwtlib/wwtlib.csproj
Let's see what we can get done here ...
> Iterate on the beta engine/client

- wwtlib/Folder.cs
- wwtlib/Graphics/Primatives3d.cs
- wwtlib/Graphics/Texture.cs
- wwtlib/Layers/LayerManager.cs
- wwtlib/Layers/VOTable.cs
- wwtlib/MinorPlanets.cs
- wwtlib/PlotTile.cs
- wwtlib/Tile.cs
- wwtlib/URLHelpers.cs
- wwtlib/Util.cs
- wwtlib/VizLayer.cs
- wwtlib/WebFile.cs
> Iterate more

- wwtlib/URLHelpers.cs
As expected, it's taking some time to work through everything ...
> Iteration 5

- wwtlib/Graphics/Texture.cs
- wwtlib/Tile.cs
- wwtlib/URLHelpers.cs
- wwtlib/WebFile.cs
OK, well I think I figured out why the all-sky data stopped working ...
> Iteration 6

- wwtlib/Folder.cs
- wwtlib/FolderUp.cs
- wwtlib/Place.cs
- wwtlib/TourPlace.cs
- wwtlib/Tours/TourDocument.cs
- wwtlib/URLHelpers.cs
- wwtlib/Util.cs
- wwtlib/WWTControl.cs
Results are looking pretty good ...
> More tidying of URL rewriting

- wwtlib/Constellations.cs
- wwtlib/Grids.cs
- wwtlib/Imageset.cs
- wwtlib/Layers/ISSLayer.cs
- wwtlib/MainView.cs
- wwtlib/MinorPlanets.cs
- wwtlib/Planets.cs
- wwtlib/SkyText.cs
- wwtlib/Tile.cs
- wwtlib/Tour.cs
- wwtlib/WWTControl.cs
Hopefully this should finish the job of making the web engine fully portable to new domains.
> Abstractify remaining wwt.o URLs

- wwtlib/WWTControl.cs
Some corner cases that have come up while working on mobile support in the revamped web client.
> Tackle zero-size canvas issues

- wwtlib/Planets.cs
And add a comment about the planet textures for posterity.
> Disentangle another URL

- package.json
- wwtlib/Properties/AssemblyInfo.cs
Let's call this 6.0.2 and get the fixes out to the people!
> Version 6.0.2

- src/index.d.ts
- src/umd_middle.js
- wwtlib/Util.cs
- wwtlib/WWTControl.cs
Expose the `startLat`, `startLng`, `startZoom`, and `startMode` parameters in a more helpful way.
> More initialization infrastructure

- .eslintrc.js
- README.md
- package.json
- src/index.d.ts
- wwtlib/FolderBrowser.cs
- wwtlib/WWTControl.cs
- wwtlib/WheelEvent.cs
Work done for the embed project.
> A grab-bag of improvements

- package.json
- wwtlib/Properties/AssemblyInfo.cs
Get the circles improvement out into the wild.
> Release 7.0.2

- azure-pipelines.yml
- embed-common/tsconfig.json
- engine-types/tsconfig.json
- engine/.gitignore
- engine/tsconfig.json
Should be prepped to release a new version of the engine and see if that CD pipeline works for non-pre-releases.
> More work on releases and CI/CD workflow

- embed-common/src/index.ts
- embed-creator/package.json
- embed-creator/src/Creator.vue
- embed-creator/src/main.ts
- embed/package.json
- embed/src/Embed.vue
- engine-helpers/package.json
- engine-helpers/src/index.ts
- engine-vuex/package.json
- engine-vuex/src/store.ts
- engine-vuex/src/wwtaware.ts
- engine/src/index.d.ts
- graduate.js
- package-lock.json
We don't offer any UI in the embed, but it's enough to be able to create something that plays back a simple tour.
> Add very basic tour playback to the embed

- docs/content/_index.md
- docs/templates/shortcodes/embed.html
- embed-creator/src/Creator.vue
- embed/package.json
- embed/src/Embed.vue
- embed/src/main.ts
- engine-vuex/package.json
- engine-vuex/src/store.ts
- engine-vuex/src/wwtaware.ts
- engine/src/index.d.ts
- engine/wwtlib/WWTControl.cs
- package-lock.json
- Add zoom controls
- Add fullscreen controls
- Fix crosshairs aspect ratio when the window size changes
- Add fullscreen and other permissions for WWT iframes
> Some embedder polish

- engine-vuex/src/store.ts
- engine-vuex/src/wwtaware.ts
Using another integral state variable that can be watch()ed to detect interesting events.
> Expose some time-control APIs in the engine Vuex vinding

- astro/package.json
- ci/azure-scriptsharp-build.yml
- embed-common/package.json
- embed-creator/package.json
- embed/package.json
- engine-helpers/package.json
- engine-types/package.json
- engine-vuex/package.json
- engine/package.json
Most recent release attempt failed, I think maybe because we need to update package-lock.json now? I've made a couple of changes to Cranko recently but I don't see how they can be causing the error that I just got.
> Fix release process (?)

- embed-common/package.json
- embed-common/src/index.ts
- engine-helpers/package.json
- engine-helpers/src/index.ts
- engine-types/src/index.ts
- engine-vuex/package.json
- engine-vuex/src/store.ts
- engine-vuex/src/wwtaware.ts
- engine/package.json
- engine/src/index.d.ts
- research-app-messages/src/classic_pywwt.ts
- research-app/package.json
- research-app/src/App.vue
Wire it up so that we can create and modify imageset layers in the app through pywwt/JupyterLab.
There is an API break in our settings system here. Not exactly worried about it impacting a lot of people.
> More work on the research app

- docs/engine/content/getting-started/embedded-app-model.md
- docs/engine/engine-vuex-index.md
- docs/engine/research-app-messages-index.md
- docs/research-app/content/embedding.md
- engine-helpers/src/index.ts
- engine-vuex/src/index.ts
- engine-vuex/src/wwtaware.ts
- research-app-messages/src/classic_pywwt.ts
- research-app-messages/src/index.ts
Resolve some of the cross-references now that an initial version of the research-app doc has been published.
> More work on documentation

- engine-helpers/package.json
- engine-helpers/src/index.ts
- engine-types/src/index.ts
- engine/package.json
- engine/src/index.d.ts
- package-lock.json
Woohoo catalog HiPS!
CC @imbasimba, FYI these are the kinds of TypeScript changes that are needed to expose new C# APIs.
> Work on exposing new catalog HiPS APIs to TypeScript

- engine-helpers/package.json
- engine-helpers/src/index.ts
- engine-vuex/package.json
- engine-vuex/src/store.ts
- engine/src/index.d.ts
- engine/wwtlib/ScriptInterface.cs
- engine/wwtlib/WWTControl.cs
- research-app-messages/src/classic_pywwt.ts
- research-app/package.json
- research-app/src/App.vue
CC @imbasimba. I'm extracting this piece of #91 to help simplify the review process for the other parts.
> New roll API for OpenSpace integration

- engine/wwtlib/SkyImageTile.cs
A slightly more elegant solution is coming with the tiled fits feature
> SkyImage non-fits fix

- package-lock.json
- research-app/package.json
General deps, and also set up to ensure that new research-app releases use the bugfixed messages library.
> Version bumps

- README.md
- ci/azure-job-setup.yml
- docs/engine/research-app-messages-index.md
- engine-types/src/index.ts
- package-lock.json
- research-app-messages/src/index.ts
- research-app-messages/src/settings.ts
- research-app/package.json
- research-app/src/App.vue
These changes should give the research app all of the features it needs in order to get pywwt passing its test suite using the app as a rendering backend!
> Add "no-chrome" mode and a few more settings

- docs/engine/research-app-messages-index.md
- engine-helpers/src/index.ts
- engine-vuex/package.json
- engine-vuex/src/store.ts
- engine-vuex/src/wwtaware.ts
- engine/src/index.d.ts
- research-app-messages/src/index.ts
- research-app-messages/src/layers.ts
- research-app/package.json
- research-app/src/App.vue
- research-app/src/CatalogItem.vue
- research-app/src/settings.ts
Add new APIs that will support pywwt access to HiPS catalogs. While I'm at it, straighten out the message dispatch framework a bit. Nothing fundamentally complicated, just more plumbing.
> HiPS catalog APIs

- embed/src/Embed.vue
- engine-vuex/src/store.ts
- research-app-messages/src/classic_pywwt.ts
- research-app-messages/src/index.ts
- research-app-messages/src/layers.ts
- research-app-messages/src/settings.ts
- research-app/src/App.vue
- research-app/src/CatalogItem.vue
- research-app/src/SourceItem.vue
- research-app/src/TransitionExpand.vue
- research-app/src/settings.ts
- research-app/src/store.ts
As requested by @astrodavid10. This has some correctness issues if the tour isn't in sky mode, but we have those issues anyway.
The only substantial code changes in this PR are in `embed/src/Embed.vue`. I also turned on auto-formatting in my VS Code which reformats a bunch of the files in a more standard way. I also fixed some linter and doc mistakes that had snuck in.
> Show default sky background menu when tours are paused

- engine/wwtlib/Layers/ImageSetLayer.cs
The test for fitsiness was only working for single FITS images.
Filing a PR to build the C# and see if this actually works ...
> engine/wwtlib/Layers/ImageSetLayer.cs: properly handle tiled-fits imagesets too

- engine-helpers/src/index.ts
- engine-helpers/src/layer.ts
- engine-helpers/src/spreadsheetlayer.ts
- engine-types/src/index.ts
- engine-vuex/src/store.ts
- engine-vuex/src/wwtaware.ts
- engine/src/index.d.ts
- engine/wwtlib/Layers/Layer.cs
- engine/wwtlib/Layers/LayerManager.cs
- research-app-messages/src/classic_pywwt.ts
- research-app/src/CatalogItem.vue
@Carifio24 OK, here is what I think we need to do to be able to wire up the app UI to control the WWT state with proper "reactive" UI magic. How does this all look to you? I'd recommend you read the changes commit-by-commit — hopefully that will give a sense as to how the pieces fit together.
I also took some inspiration from [this post] for how to approach the general state storage.
[this post]: https://forum.vuejs.org/t/vuex-best-practices-for-complex-objects/10143/2
If we go with this approach, I can go through and flesh out the "settings" frameworks for the rest of the objects that need it — there are a lot of them, but it's all pretty rote work.
The bottom line is that I'm pretty sure that we need to do this mirroring of WWT objects for the Vue(x) reactive UI magic to work. It …
> Work on reactive settings

- docs/engine/engine-vuex-index.md
- engine-helpers/src/annotation.ts
- engine-helpers/src/circleannotation.ts
- engine-helpers/src/engine.ts
- engine-helpers/src/imagesetlayer.ts
- engine-helpers/src/index.ts
- engine-helpers/src/polyannotation.ts
- engine-helpers/src/polylineannotation.ts
- engine-helpers/src/votablelayer.ts
- engine-types/src/index.ts
- engine-vuex/src/index.ts
- engine-vuex/src/store.ts
- engine-vuex/src/wwtaware.ts
- engine/src/index.d.ts
- research-app-messages/src/classic_pywwt.ts
- research-app/src/App.vue
Set up more Vue(x) infrastructure to expose more settings reactively, this time with ImageSet layers.
**updated:** This is working towards a basic UI for dealing with FITS-like layers, including tiled FITS. I prototyped all of the functionality here but am now breaking it into a series of PRs to make it more reviewable.
> Work on reactive settings, FITS layer UI in the app

- engine-vuex/src/store.ts
- engine-vuex/src/wwtaware.ts
- package-lock.json
- research-app/package.json
- research-app/src/App.vue
- research-app/src/ImagesetItem.vue
- research-app/src/main.ts
- research-app/src/store.ts
- tests/page_objects/researchApp.ts
- tests/research_app/basic_test.ts
Final pull request in the series. Adds the new UI, similar to the catalog and source UIs.
To demo the functionality:
1. Run research app
2. Use new Load WTML Collection tool and load: http://data1.wwtassets.org/packages/2021/08_hscfits/index.wtml
3. Use new Add Imagery as Layer tool and add "HSC-Sample"
4. Experiment with the new UI
CC @imbasimba for visibility.
> FITS UI part 4: the actual research app UI

- embed/package.json
- engine-helpers/package.json
- engine-vuex/package.json
- engine/package.json
- research-app/package.json
We've added lots of features everywhere, so we basically bump up the deps of every modified package to require the latest code.
CC @Carifio24, FYI
> Update Cranko internal version requirements

- research-app-messages/src/classic_pywwt.ts
- research-app/src/App.vue
This allows us to get more user-friendly names of the image layers
> Added name parameter for create image layer messages

- engine-vuex/package.json
- engine/package.json
- research-app/package.json
Update some internal version requirements and make the engine's new external deps explicit.
> Some release tidying

- .config/cranko/config.toml
- research-app/package.json
- Update Cranko internal version requirements
- Add new Cranko ignore flags for things that we don't want to actually be projects
> Some small tidying for next releases

- engine-vuex/package.json
- engine-vuex/src/store.ts
- engine-vuex/src/wwtaware.ts
- engine/src/index.d.ts
- research-app-messages/src/index.ts
- research-app/package.json
- research-app/src/App.vue
- research-app/src/store.ts
Update Cranko internal dependencies, tidy up whitespace and formatting.
> Tidying for release

- ci/azure-deployment.yml
I got an error in the most recent builds:
```
The term 'Unpublish-AzCdnEndpointContent' is not recognized [...]
```
Based on <https://github.com/Azure/azure-powershell/issues/19241>, I am trying this change to attempt to fix it. Unfortunately there isn't really a way to test besides merging and seeing what happens.
> ci: attempt to fix CDN purge step

- docs/engine/content/freestanding-mode/_index.md
- docs/engine/engine-index.md
- embed/package.json
- engine-helpers/package.json
- engine-helpers/src/index.ts
- engine-pinia/package.json
- engine-pinia/src/Component.vue
- engine-pinia/src/wwtaware.ts
- engine/src/index.d.ts
- engine/wwtlib/Constellations.cs
- engine/wwtlib/Folder.cs
- engine/wwtlib/FolderUp.cs
- engine/wwtlib/Grids.cs
- engine/wwtlib/Imageset.cs
- engine/wwtlib/Layers/ISSLayer.cs
- engine/wwtlib/Layers/LayerManager.cs
- engine/wwtlib/Layers/SpreadSheetLayer.cs
- engine/wwtlib/MinorPlanets.cs
- engine/wwtlib/Place.cs
- engine/wwtlib/Tile.cs
- engine/wwtlib/Tour.cs
- engine/wwtlib/TourPlace.cs
- engine/wwtlib/URLHelpers.cs
- engine/wwtlib/WWTControl.cs
- research-app/package.json
- tests/package.json
- yarn.lock
The goal here is to give us a version of the engine that starts up without accessing any resources from `worldwidetelescope.org`, for users who just want WWT as a freestanding visualization widget.
~This is currently *draft* work but by filing the PR I get the CI building and checking the C# changes.~
> "Freestanding" mode

- engine/src/index.d.ts
URLHelpers is needed in the WWT Constellations project
> Exposed URLHelpers to TypeScript

- ci/azure-main-build.yml
- docs/engine/config.toml
- docs/research-app/config.toml
Just fixing up some issues of CI versus my local machine.
> Some fixes for the tutorial as deployed

- engine/esm/layers/layer_manager.js
- engine/esm/planets.js
- engine/esm/planets_3d.js
The relevant code in the Windows client hadn't been imported, it seems. Fortunately it seems like we can pull it in straightforwardly!
Also fix some related bugs that I noticed while investigating this.
> Draw orbits of Galilean moons

- engine/esm/annotation.js
This is a longstanding bug that I've never gotten around to fixing. The previous code used a magic constant of 44 to go from the nominal circle radius in degrees to the number actually used in the shader. In StarHunt I had realized that this was missing a cos(dec) correction, as well as a constant prefactor. With the cos(dec) applied, `44 * prefactor` is almost exactly equal to 180 / pi, and using that number to set the sizing yields results that look perfect. My guess is that the 44 came from some manual futzing with a test circle at a dec of 40 degrees, which would yield that number if you didn't realize that the cos(dec) term was necessary.
Closes #297.
> engine: fix sizing of circle annotations

- ui-components/package.json
This does some more dependency setup for the new package.
> Add more WWT dependencies for ui-components
