WorldWideTelescope/wwt-webgl-engine

wwtlib/URLHelpers.cs

I thought I was so smart to not worry about the capitalization of domain names ... but capitalization does matter for some of our URLs that have `{}` templates in the domain name.

wwtlib/URLHelpers.cs: fix a bit of a corner-case in URL rewriting

---

wwtlib/Graphics/Texture.cs
wwtlib/Planets.cs
wwtlib/Tile.cs
wwtlib/URLHelpers.cs
wwtlib/WebFile.cs

If a tile or file get fails on a URL that comes from the flagship domain, we know that the proxy won't help. So in those cases, don't bother with retries.

Avoid retrying with the webproxy when we know it won't help

---

wwtlib/Graphics/Texture.cs
wwtlib/Tile.cs

Otherwise the tile cache thinks that it has no capacity left in its download queue and stops trying to fetch anything. That's bad.

Need to properly mark tiles as failed if we don't retry them.

---

wwtlib/Folder.cs
wwtlib/Layers/VOTable.cs
wwtlib/PlotTile.cs
wwtlib/Tile.cs
wwtlib/URLHelpers.cs

I've had a feeling for a while that I'd need to add this, and this was spurred by issues with the production beta webclient having problems loading a folder with URL `../Resource/...`.
I want a mode parameter here because if we load up a WTML file that contains a relative URL, that URL should be absolute-ified relative to the source of the WTML file, not the window origin. Right now, relative URLs in WTML files are not allowed, but I'd like that to change one day. (If/when we implement this, this function will probably need to acquire a third parameter to give the base URL to use in the relative-to-something-else case.)

wwtlib/URLHelpers.cs: add a mode parameter to URLHelpers.rewrite()

---

wwtlib/URLHelpers.cs

At the moment this is always set to web.wwtassets.org, which is a CDN-ified version of the `wwtwebstatic` static website served off of our storage account.
The motivation here is that cdn.worldwidetelescope.org is always going to have to route its requests through worldwidetelescope.org, which means they will have to go through the App Gateway reverse proxy before, in the case of web static assets, eventually being routed to `wwtwebstatic`. By using a different CDN endpoint, we can cut out the App Gateway middleman, which should reduce load on that service, hopefully be faster, and hopefully save us some money.
Like many other big websites, we use a separate second-level domain, namely the new wwtassets.org. The apparent motivation is that that way you don't have the cookies from your …

wwtlib/URLHelpers.cs: add a web_static_baseurl parameter

---

azure-pipelines.yml

When a pull request is merged to master, it will be uploaded to the `engine/latest` directory on the Azure Storage. When a version tag is pushed, it will currently be uploaded to (e.g.) `engine/1.2.3`. Here we add another stanza to also uploaded tagged release to a "major.minor" directory, e.g. `engine/1.2`. This way, a web app that wants to get bugfixes can just target the `1.2` directory and not have to track every individual release. This is of course assuming a semver model where micro updates do not break anything.
We may need to purge the CDN cache upon releases in order for this workflow to fully work. It looks like that can be automated as well.

azure-pipelines.yml: also publish version tags to a `major.minor` directory

---

package.json
wwtlib/Properties/AssemblyInfo.cs
wwtlib/URLHelpers.cs

We're ready to go live with the new infrastructure. In 6.0.1 we default the engine to point at the main worldwidetelescope.org domain for unknown origins, rather than the beta-test domains.

Release 6.0.1

---

package.json
wwtlib/Properties/AssemblyInfo.cs

This PR includes the commit that will become the 7.0.1 release tag. That release fixes the critical `Enum.parse` bug in 7.0.0.

Release 7.0.1

---

azure-pipelines.yml

Will need to add steps to deploy new versions of the embed and the embed creator eventually, but let's see if these work.

ci: attempt to wire engine and docs deployment steps back in

---

embed/package.json
embed/tsconfig.json
graduate.js

I had to manually push an update to `release` before this PR to allow for a successful merge of the change that adds the `embed-common` dep to `embed`. We then needed to add additional, non-conflicting commits to this branch so that the PR and `master` CI processes have something new to merge into `release`.
We also add a change to `graduate.js` that will, I hope, fix the versioning problem of `embed` that will allow us to have a package definition that simultaneously builds locally *and* can be published as a freestanding package.

CI/CD iteration: try to fix `embed` release process

---

embed-creator/src/Creator.vue
embed/package.json
embed/public/index.html
embed/src/Embed.vue
embed/src/main.ts
embed/src/v-tooltip.d.ts
engine-helpers/src/index.ts
engine-vuex/src/Component.vue
engine-vuex/src/store.ts
engine-vuex/src/wwtaware.ts
engine/src/index.d.ts
engine/wwtlib/RenderContext.cs
package-lock.json
package.json

We add an icon with a popup menu that provides a few tools for playing with the WWT view. The initial offerings are:
- Image crossfader, when there's a foreground image
- Background chooser, when in sky mode.
Plus plumbing to make it all possible and robust, I hope.
Also make the embed view default to point at the Galactic center.

Add a few "tools" in the embed

---

embed-creator/package.json
embed/package.json
engine-helpers/package.json
engine-vuex/package.json

Sigh. I rewrote history to get a minimal set of changes to merge into `release` in order to make the `tours` branch mergeable, but I didn't think that would invalidate all of the commit ID's that I embedded in the local package version requirements. Fix those up.

build: fix commit references

---

engine/wwtlib/URLHelpers.cs

We preloaded the engine URL helpers to know not to try to proxy the localhost domain, but it turns out that `localhost:8080` is treated separately from just `localhost`. Add some logic to detect these domains and recognize them as localhost-y if needed.
Without this, if you try to load files off of something like `localhost:8080`, e.g. a local tiled image for testing, 404's can cause the engine to start trying to proxy everything which breaks all further downloads.

fix(engine): don't attempt to proxy localhost URLs on nonstandard ports

---

engine/wwtlib/Tile.cs
engine/wwtlib/URLHelpers.cs

See if we can work around the reported issues by notifying the engine that it doesn't need to proxy wwtfiles anyway.
I am still totally befuddled as to why sometimes the proxy returns 0 bytes for certain of the tiles intermittently. You'd think that Squid would be reliable enough to not get this wrong, so my hunch is that the Azure Blob Storage servers are indeed sometimes returning zero-sized responses. But in my digging I'm unable to find any reports of this, thus far.

WWTA fixes

---

azure-pipelines.yml

We're trying to preserve semver and we want users to get the latest stuff, so it will be much more convenient to not need to update them every time a minor release comes out. With semver semantics, we expect our version numbers to evolve as `tiny.large.small`, not `tiny.small.large`.

azure-pipelines.yml: publish engine JS to /$major/, not /$major.$minor/

---

engine/wwtlib/Place.cs

This was using `descriptionNode.Value`, which translates to `descriptionNode.nodeValue` in JavaScript. This just doesn't work, because for element nodes that value is always null. I believe this was inherited from the Windows implementation, where the description content is an XML CDATA section, which sometimes requires special handling. But really CDATAs ought to be fully transparent to us. Just use our existing `GetInnerText` utility.
I'm not 100.00% sure that this doesn't break compatibility with the old code, but nothing in production has ever used this field, so I'm comfortable going for it.

engine/wwtlib/Place.cs: use GetInnerText to get Place.Description text

---

embed-creator/src/Creator.vue

We need to embed `http://` inside WTML files for compatibility with the Windows client, but for URLs that are passed through the web APIs, we should always (?) use HTTPS to avoid security issues if someone is viewing something over an HTTPS connection.

embed-creator: use https:// for sample URLs

---

ci/azure-deployment.yml
ci/azure-job-setup.yml
ci/azure-main-build.yml
ci/azure-scriptsharp-build.yml

My first fix attempt didn't work. I think I have a better idea of what's happening now — Lerna is a bit simple and was confused by our internal version requirements. Hopefully this will fix things for real, although I don't think I can fully find out without attempting another release.

Release pipeline fix, take 2

---

embed-creator/package.json
research-app-messages/src/classic_pywwt.ts

We need a little shim to successfully exchange data between Jupyter(Lab) and the research app.

Add URL-rewriting to research-app-messages

---

engine/wwtlib/HealpixTile.cs
engine/wwtlib/HipsProperties.cs
engine/wwtlib/IImageSet.cs
engine/wwtlib/Imageset.cs
engine/wwtlib/Layers/Layer.cs
engine/wwtlib/Layers/LayerManager.cs
engine/wwtlib/Layers/SpreadSheetLayer.cs
engine/wwtlib/Layers/VOTable.cs
engine/wwtlib/Layers/VoTableLayer.cs
engine/wwtlib/RenderContext.cs
engine/wwtlib/ScriptInterface.cs
engine/wwtlib/Tile.cs
engine/wwtlib/UiTools.cs
engine/wwtlib/WWTControl.cs
engine/wwtlib/WebFile.cs

All Catalog HiPS entries here need to change: http://www.worldwidetelescope.org/wwtweb/catalog.aspx?W=hips
From: DataSetType="Sky"
To: DataSetType="CatalogHips"
Catalog entries should also be added here: http://web.wwtassets.org/engine/assets/builtin-image-sets.wtml

Catalog HiPS

---

engine/wwtlib/HealpixTile.cs
engine/wwtlib/Layers/FitsImage.cs

As expected it is quite slow, but it is technically working. 
There seem to be a bug in FitsImage.cs when dealing with the "no data" pixels of the FITS files. For some tiles they are grey, and other they are black. I have not investigated the issue as this entire PR is just a proof of concept for the real solution of reading the data from the shader.

Simple FITS HiPS support using JavaScript parsing

---

engine/wwtlib/WWTControl.cs

Since the engine only loads a subset of the imagesets, it is required to add catalog HiPS by sending the entire imageset instead of just the name.
Needed for this one
https://github.com/WorldWideTelescope/wwt-web-client/pull/344

Add catalog HiPS by imageset

---

embed/src/Embed.vue
engine-helpers/src/index.ts
engine-vuex/src/store.ts
engine-vuex/src/wwtaware.ts
engine/src/index.d.ts
engine/wwtlib/Folder.cs
engine/wwtlib/Layers/LayerManager.cs
engine/wwtlib/ScriptInterface.cs
engine/wwtlib/Utilities/Histogram.cs
engine/wwtlib/WWTControl.cs
engine/wwtlib/Wtml.cs
research-app-messages/src/classic_pywwt.ts
research-app/src/App.vue

1. Option to recursively download Folders in a WTML
2. Added optional parameter to set roll of camera
3. Can now add regular image sets to LayerManager via postMessage / research-app messages
4. Disallowed duplicate image sets (pointing to the same URL) & started using image set url as a semi user friendly identifier
@pkgw Do you know what the TODO comment in Folder.cs:371 is referring to? I removed the "true" thing mentioned in the TODO, so it may cause some problem.

OpenSpace patch

---

engine-vuex/src/store.ts
engine-vuex/src/wwtaware.ts
engine/src/index.d.ts
research-app/src/App.vue

This is pull request #99 by @Carifio24, plus a couple of tweaks. Normally GitHub lets me add new commits directly onto the branch that's sourcing the pull request, but I'm not allowed to do that in #99, I think because it's being sourced from `master` and not from a feature branch.
Tweaks are:
- Oops, the parity on the left/right keyboard controls was swapped!
- Additional keybindings building on the nice framework we now have:
- Arrow keys for pans
- Alt+(arrow keys) for rolls and titls
- Shift+(arrow keys) and Shift+(IJKL) for "big" pans, six times the size of the default ones
- Also swap the parity for the left/right rolls; the new way feels more "right" to me
- Fix a warning issued by Vue in the browser console saying that the default value for the keyboard controls struct should be …

Keyboard controls, plus a few extensions

---

engine-vuex/src/store.ts
engine-vuex/src/wwtaware.ts
engine/src/index.d.ts
research-app/src/App.vue

Adds keyboard support for zooming, moving, and tilting the WWT viewer. The mapping between keys and events is based on KeyboardEvent.key, which [per MDN](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key) has support on all browsers.

Add keyboard support for WWT viewer control

---

research-app/src/App.vue

Move the z-index statement to keep the hamburger menu clickable (closes #107), and add a max-width and ellipsization to shrink the selector in narrow windows.
CC @Carifio24

research-app: small fixups for background selector

---

research-app/src/App.vue

OpenSpace encountered an intreresting issue when deploying the research app to an http server.
See browser console here:
http://www.winterway.eu/wwt-http-problem/index.html?origin=http://www.winterway.eu
The short story is that ServiceWorker is undefined if a user connects with http instead of https, as you can see by connecting to the same code with https:
https://www.winterway.eu/wwt-http-problem/index.html?origin=https://www.winterway.eu
I tested this PR here, and it seems to be working fine on http:
http://www.winterway.eu/wwt/index.html?origin=http://www.winterway.eu
(ServiceWorker is defined on http conenction if the host is localhost, that's why at least I haven't seen the issue before)
@pkgw Do you remember the reasoning behind the `!instanceof MessagePort && !instanceof …

Undefined check for ServiceWorker

---

research-app/src/App.vue

Follow up to:
https://github.com/WorldWideTelescope/wwt-webgl-engine/pull/111 
I just tested this simplified type guard and it seems to be working fine.
I have not seen any compiler warnings or errors (at least with my setup), so maybe the issue requiring the odd type guard has been fixed.

Simplified type guard

---

embed/src/Embed.vue

Adds support for panorama images in the embed app. If the given image in the WTML is a panorama, it's set as both the foreground and background images, since a foreground image is required for SetupForImagesetOptions.

Add support for panorama images to the embed app

---

research-app-messages/src/classic_pywwt.ts
research-app/src/App.vue

Doing something more generic is also an idea, like this for example:
`this.statusMessageDestination.postMessage({event: msg.event + "_completed", originalMessage: msg}, this.allowedOrigin);`
Then the same style could be used for all async events, where the client may want to know when something has completed.

Posting image_collection_loaded event on folder load complete

---

engine-vuex/package.json
research-app/package.json

Vuex needs the new engine APIs, and the research app needs the new features in Vuex and research-app-messages.

Release prep: update Cranko minimum versions

---

docs/engine/research-app-messages-index.md
research-app-messages/src/classic_pywwt.ts
research-app-messages/src/index.ts
research-app/package.json
research-app/src/App.vue

In order to make the Research App work well as a replacement for the hand-coded ipywidgets viewer in pywwt, we need to add and modify some messages:
- a "ping-pong" API for the Jupyter client to poll when the app has started up. The JupyterLab extension should also be using this.
- a "session ID" field for the unsolicited view-state messages, to allow the client to figure out which view those messages came from
- a "thread ID" field for the load-image-collection request and response, for similar reasons
The basic thing going on here is that in the ipywidgets case, we might have multiple widgets, each of which can have multiple app "views", and the widget bridge code can't tell whose messages came from where. Also, AFAICT there's no way for the client to know when the app is ready to …

Research App messages to support Jupyter/ipywidgets implementation

---

research-app-messages/src/classic_pywwt.ts

The "mode" field of the CreateImageSetLayerMessage should be optional. This manifested because the type guard function would return false for should-be-valid messages from older versions of pywwt, breaking FITS image loading in the JupyterLab app.

research-app-messages: fix accidental back-compat breakage

---

engine/wwtlib/Graphics/Shaders.cs
engine/wwtlib/HealpixTile.cs
engine/wwtlib/Imageset.cs
engine/wwtlib/Layers/FitsImageJs.cs
engine/wwtlib/SkyImageTile.cs
engine/wwtlib/TangentTile.cs
engine/wwtlib/Tile.cs
package-lock.json
research-app-messages/src/classic_pywwt.ts

Engine support of tiled FITS! 🎆 
Test it:
1. https://winterway.eu/wwt-tiled-fits/index.html?origin=https://winterway.eu
2. postMessage({event: "load_image_collection", url: "https://winterway.eu/wwt-tiled-fits/index_rel.wtml"})
3. postMessage({event: "image_layer_create", id:"tiled-fits", url: "https://winterway.eu/wwt-tiled-fits/{1}/{3}/{3}_{2}.fits", mode:"preloaded", goto:true})
4. postMessage({event: "image_layer_stretch", id:"tiled-fits", stretch: 0, version: 1, vmin: 0, vmax: 1.01})
You can load the orignial fits with:
postMessage({event: "image_layer_create", id:"single-fits", url: "https://winterway.eu/wwt-tiled-fits/IRAC.fits", mode:"fits", goto:true})
The deployed version at https://winterway.eu/wwt-tiled-fits has two differences as compared to if you run this yourself with a …

Tiled FITS support + Merged SkyImage and TangentTile

---

research-app/src/App.vue
research-app/src/CatalogItem.vue
research-app/src/SourceItem.vue

@Carifio24 Here are some suggested changes to try to tighten up the presentation of the research app panel:
- Give the panel a transparent background, as opposed to giving the whole thing a 60% opacity. The latter approach makes it so that nothing within the panel shows up at full intensity
- Tighten up the internal margins. `<p>` elements have to have their margins zeroed so as not to add undue vertical spacing
- Downscale the section headings ("Sources:" etc), using a little inline rule effect instead
- Ellipsize catalog and source names rather than letting them wrap
- Give them a `vertical-align: middle` to even out their presentation by a few pixels
- Kill redundant background settings in the catalog and source item components
- Add some extra `cursor: pointers` when hovering over …

research-app: tighten up the panel presentation a bit

---

research-app/src/CatalogItem.vue
research-app/src/main.ts

I spent a surprisingly long time trying to figure out the UI here. I started with a slider, but I couldn't figure out a way to make that work given the large dynamic range needed by the scale-factor parameter. Then for numeric inputs, the basic web browser styling is dissatisfactory, but I couldn't find an powered-up Vue input widget with good TypeScript bindings. So I slightly rolled my own.

Add a scale factor control for HiPS catalogs

---

research-app-messages/src/index.ts
research-app-messages/src/selections.ts
research-app/src/App.vue
research-app/src/store.ts

This PR adds a new message type, `SelectionStateMessage`, to `research-app-messages`, as well as functionality in the research app to broadcast these messages at appropriate times. Currently, the items that are broadcast on a change are the list of selected HiPS catalogs, the list of selected sources, and the most recent selected source.
I'm not sure if this is exactly how we want to handle the most recent selected source (which would be useful for e.g. `glue-wwt`). As things are now, every time a new source is selected, messages are broadcast for both the list of sources and the most recent source, which feels redundant. The alternative, I think, would be to only broadcast the source list message, and leave it on the user to identify whether the last source in the list is new or not.

Research app selection messaging

---

engine/src/index.d.ts
engine/wwtlib/FitsProperties.cs
engine/wwtlib/HealpixTile.cs
engine/wwtlib/Imageset.cs
engine/wwtlib/Layers/FitsImage.cs
engine/wwtlib/Layers/ImageSetLayer.cs
engine/wwtlib/Layers/LayerManager.cs
engine/wwtlib/ScriptInterface.cs
engine/wwtlib/TangentTile.cs
engine/wwtlib/WWTControl.cs
package-lock.json

This PR makes various changes to the engine that were needed to get the FITS UI/UX going. Specifically:
- Add some existing APIs to the TypeScript exports (especially the LayerMap pieces)
- Provide a mechanism to properly set up the FitsProperties of tiled FITS files. This needs some new notification APIs to be set up. The existing HiPS FITS code didn't need this because it could respond to the download the HiPS "properties" file, but plain tiled FITS doesn't have that
- And set up non-HiPS tiled FITS to use the above mechanism with some custom FITS headers in the level-0 tile
- Add a hook to guess an appropriate zoom level when going to an Imageset. Ideally, imagesets should be wrapped in Place objects which can specify the desired view exactly, but this isn't always available
- Also …

FITS UI part 2: engine features

---

engine-vuex/src/store.ts
engine-vuex/src/wwtaware.ts

Here we add a few more hooks to the engine-vuex module to help the frontend know what the active layers are. The code that manages the spreadsheet layers should be updated to use the same infrastructure ­— the LayerMaps hierarchy is the correct source of truth for this information.

FITS UI part 3: engine-vuex extensions

---

research-app/src/App.vue

Easing myself into this again with a really simple PR. 
Basically there is always an area of 0.75rem height that cannot be interacted with since it is covered by vue-notification-group. When the notification is showing the area is even bigger making the control button and part of the zoom button.

Fix for uninteractable area around notifications

---

engine/wwtlib/FitsProperties.cs
research-app/src/App.vue

As discussed, the transparentBlack property is now off by default, just like the current pywwt behaviour.
Also two tiny changes
1. to open a help link in a new tab 
2. fixed unnecessarily wide display-panel for larger screens.

Transparent black disabled by deafault

---

research-app/src/App.vue
research-app/src/CatalogItem.vue
research-app/src/SourceItem.vue
tests/page_objects/researchApp.ts

This PR contains a few small UI updates to the research app. I'm still working on adjusting the overall UI layout based in response to screen size, but I can see that requiring some discussion and iteration, so I'm thinking that can go in its own PR.
The changes in this PR are:
- Retain the `border-radius` of the bottom item in the display panel when it's highlighted. Currently, when the bottom item is highlighted, its bottom corners return to being rectangular. I suspect that the structure in the panel items in the panel changed at some point and the CSS hadn't been updated to match.
- Ellipsize the items in the dropdown selectors to avoid horizontal scrolling in the dropdowns, as well as the selected items (i.e. for the backgrounds and imagery layers).
- Change the container with the …

Research app UI updates

---

embed/src/Embed.vue
tests/page_objects/researchApp.ts

This PR fixes an issue with embeds not recognizing Places correctly, which arises from the `places` field of the `Folder` class not being populated. This fix changes the iteration over `places` to one over `children`, together with an appropriate type check.

embed: Fix issue with Places not being recognized in WTML

---

research-app/src/CatalogItem.vue
research-app/src/ImagesetItem.vue
research-app/src/SourceItem.vue
tests/page_objects/researchApp.ts
tests/research_app/basic_test.ts

This PR changes the source entries in the display panel to use a flexbox-based layout to match the catalog and imageset containers. Additionally, using `ImagesetItem` as the base, I made the buttons have uniform size and spacing across all of the containers.

Research app display panel UI

---

research-app/src/App.vue

This PR modifies the research app UI to be more responsive to changes in screen size. This is done via flexbox layouts (sometimes nested). The main things that this layout looks to achieve are the following:
- Keep the selection tools centered on the screen while preventing any overlap with the display panel. The top-level flexbox containers that wrap the display panel, tools, and controls have `flex` values of 2, 3,  and 2, respectively, which means that the share of horizontal space allocated to the `display-panel-box` is 2/7, or about 28%. The display panel has a `max-width` of `25vw`.
* Using 1,2,1 gives the display panel no extra space inside of its container (unless the browser is spanning multiple monitors), which I thought looked worse when shrinking the screen size. Using 4, 7, 4 …

Research app UI element sizing and positioning in response to screen size

---

engine-vuex/src/index.ts
engine-vuex/src/store.ts
engine-vuex/src/wwtaware.ts
research-app-messages/src/selections.ts
research-app/src/App.vue
research-app/src/SourceItem.vue
research-app/src/SpreadsheetItem.vue
research-app/src/main.ts
research-app/src/store.ts
tests/page_objects/researchApp.ts

This PR adds initial support for manipulating user-added table layers via the UI, and selecting sources present in these layers. The main idea is as follows:
- I added a `SpreadSheetLayerInfo` class, analogous to `ImagesetInfo` that we were using for the HiPS catalogs, which contains the relevant information for the display panel and research app store about a spreadsheet layer.
- `CatalogItem` has been renamed to `SpreadsheetItem` (and its `catalog` prop renamed to `layer`). The `layer` prop now has type `LayerInfo = ImagesetInfo | SpreadSheetLayerInfo`. Since these layer types, and the corresponding info classes, are pretty similar, a few `v-if` statements and some delegation in the delete method are enough to handle pretty much all of the differences. Since the engine-generated names …

Allow UI manipulation and selection of general table layers

---

package-lock.json
package.json
tests/package.json
tests/page_objects/researchApp.ts
tests/research_app/basic_test.ts
tests/utils.ts

This PR focuses on two items. First, I've added in a test of the WTML loading and imagery layers, using the [PHAT](http://data1.wwtassets.org/packages/2021/09_phat_fits/index.wtml) FITS data as the sample. This is a pretty straightforward test, similar to what we had for the HiPS catalogs plus the WTML loading - load the file, check that we have the right number of layers, then select the first layer and check that the display panel behaves correctly.
Second, I've tried to remove some of the obvious stress points that we'd noticed. In particular:
- I added a utility function to help with automatically creating `RegExp` objects from strings.
- I added some code to count the numbers of available HiPS catalogs and background imagesets from the appropriate URLs …

Add PHAT imagery test and bolster test code

---

research-app/src/ImagesetItem.vue

This PR makes the UI elements of an imageset item in the display panel shrink appropriately to fit the display panel size (currently they can be hidden when the display panel shrinks).
The "Colormap" and "Stretch" `select`s now shrink to fit within the item container, as do the `input`s for the low and high cutoffs. I allowed the cutoff inputs to grow with the display panel, since they display a large number of decimal places. I also set the prompt labels for the two cutoff fields to have a fixed width (`84px`). Without this, on every screen that I tried, the "Low cutoff" and "High cutoff" labels were _almost_ the same width, and the small difference made the two rows look sloppy. We could line up all of the inputs/selects if we wanted, but it would waste some space, particularly on the …

research-app: Tweak imageset panel items

---

engine/wwtlib/HealpixTile.cs

Simple fix to handle planetary HiPS. Really cool with the latest Planets & Moons category from https://github.com/WorldWideTelescope/wwt-hips-list-importer/commit/1b227fec7f644ad99c2da092451c37dde76866cd
There is definitely a more accurate way of calculating whether the tile is big enough. For example, calculating the number of screen pixels currently covered by either of the tile sides while also taking into account that the number of pixels per tile can vary in different HiPS. But this very simple heuristic actually seems to work quite well.

Prepared HealpixTile for planetary HiPS

---

research-app/package.json

They all have bugfixes and/or new features needed for the cool new startup scripting feature.

research-app: require latest releases of internal dependencies

---

research-app/src/App.vue

I think this PR should do the trick as far as fixing up `statusMessageDestination` issue that was popping up in the release version of the app. Basically, the idea is to do something similar to what we do with `allowedOrigin`: if there is a query script present, we set `statusMessageDestination` early as the current window. In this case, it's in the `then` block after `waitForReady` rather than in `main.ts`. To facilitate this, I split out the part of the code that grabs the query script.
Also, this PR fixes another bug in the query message handling that was causing the wrong message handler to be removed when a message type that needs a reply was completed. (This is on what is now line 1514). Now, after the query script initialization is complete, the message handler table is left in the …

research-app: Fix issue with query scripting

---

engine/wwtlib/Annotation.cs
engine/wwtlib/Graphics/Primatives3d.cs

This reduces the memory usage of filled circles by >98%. While this can be improved further, this is the 20% of the effort giving 80% of the value. 
The performance is still not optimal when showing thousands of filled circles, but now it is at least functional. 
With the previous implementation the inside of the circle was filled with 1136 triangles. Each of these triangles have 3 points. Each of the points have a position (x, y, z), a normal (x, y z), a start date and end date, a color (rgba). So, in total, filling a circle required 1136 * 3 * (3 + 3 + 1 + 1 + 4) = 40 896 numbers. So no wonder there were some issues :smile:
The new implementation reduces the number of points to 74 and removes the normal -> 74 * (3 + 1 + 1 + 4) = 666 numbers per filled circle. 
With some changes, we …

Filled annotation circle performance improvement

---

engine/wwtlib/HealpixTile.cs
engine/wwtlib/TangentTile.cs
engine/wwtlib/WebFile.cs

The WebFile State for localhost urls, or requests tagged with WWTFlagship or NeverProxy were never updated if the request failed. So the users of WebFile were never notified that a problem occurred. This was especially noticeable when loading HiPS from localhost, which often requests tiles that don't exist.
I also attached a small update to correct the error state of FitsImageJs (used by browsers not supporting WebGL2) in case of errors.

Webfile localhost error

---

engine/wwtlib/Coordinates.cs
engine/wwtlib/Layers/SpreadSheetLayer.cs

This PR is aimed at fixing the cause of #34. I think the culprit is [SpreadSheetLayer.GeoTo3dDoubleRad](https://github.com/WorldWideTelescope/wwt-webgl-engine/blob/master/engine/wwtlib/Layers/SpreadSheetLayer.cs#L826), which adjusts the longitude of the point by 180 degress before performing the transformation.
This function is currently called in five places:
[SpreadSheetLayer.cs, line 826](https://github.com/WorldWideTelescope/wwt-webgl-engine/blob/master/engine/wwtlib/Layers/SpreadSheetLayer.cs#L826)
[SpreadSheetLayer.cs, line 1211](https://github.com/WorldWideTelescope/wwt-webgl-engine/blob/master/engine/wwtlib/Layers/SpreadSheetLayer.cs#L1211)
[SpreadSheetLayer.cs, line 1212](https://github.com/WorldWideTelescope/wwt-webgl-engine/blob/master/engine/wwtlib/Layers/SpreadSheetLayer.cs#L1 …

Fix SpreadSheetLayer longitude values

---

ci/azure-job-setup.yml
package-lock.json

There's something about the internal dependency versioning that seems to break Lerna bootstrapping when making some releases — but it only shows up then because in CI environments, Lerna uses `npm ci` instead of `npm install`. ... Unless we tell it not to, mwah hah hah!

Avoid Lerna bootstrapping error when making releases

---

research-app-messages/src/selections.ts
research-app/src/App.vue
research-app/src/store.ts

This PR adds the ability to toggle whether or not the sources in a given table layer are selectable. This toggling can be done either in the UI or programmatically via a message. My motivation for this was from investigating the `glue-wwt` speed issue when using the newest version of `pywwt`. I believe that issue pops up when there are a lot of points visible due to the nearest-source calculation slowing things down. Removing layer selectability should increase performance - in particular, if no layers are selectable, `closestInView` doesn't need to do any work. From testing on my machine, this did indeed seem to be the case. Aside from glue, though, I think any client embedding the research app benefits from this if they don't want source selection - performance should be increased and …

Allow toggling whether sources from a given layer are selectable

---

engine/wwtlib/HealpixTile.cs
engine/wwtlib/TangentTile.cs
engine/wwtlib/Tile.cs

Moved FITS processing to base class (Tile.cs). Now any tile (including TOAST) using the base class implementation of MakeTexture and RequestImage is able to reder FITS images.
Bonus points for having more row deletions than additions :)

TOAST FITS support

---

research-app/src/App.vue

I thought I had covered all of our bases when making the HiPS catalog name --> id conversion, but this PR fixes an issue that slipped through the cracks. Essentially, in `stateAsUrl`, the messages that restore settings on HiPS catalogs in the URL export are currently still using the dataset name, rather than the layer ID, for identifying the layer. This doesn't work since we gave the `tableId` earlier in the method as the layer ID, and so the settings don't get applied. This PR changes the `id` field of the settings message to use the layer ID rather than the dataset name.

Use layer ID in query script catalog messages

---

engine/wwtlib/Layers/Layer.cs

Currently the engine won't create a `VoTableLayer` from XML (e.g. from a tour), because `"VoTableLayer"` is missing as an option in the switch statement here. This PR fixes this issue by adding the appropriate case.
This partially resolves #182. It doesn't fix the colormap issue, which is a separate problem and will potentially require a bit of thought. As far as I can tell, `SpreadSheetLayer` also doesn't support the full set of colormap options (such as the one used in the tour referenced in the issue), so maybe updating those together can be done a later PR.

Allow creating VoTableLayer from XML

---

package-lock.json
package.json
tests/utils.ts

While building with the current `package.json`, one gets the following error with one of Vue's type declaration files:
```
> @wwtelescope/research-app-messages@0.0.0-dev.0 build /home/jon/dev/WWT/test/research-app-messages
> tsc
lerna ERR! npm run build exited 2 in '@wwtelescope/astro'
lerna ERR! npm run build stdout:
> @wwtelescope/astro@0.0.0-dev.0 build /home/jon/dev/WWT/test/astro
> tsc
../node_modules/vue/types/jsx.d.ts(39,7): error TS1110: Type expected.
../node_modules/vue/types/jsx.d.ts(39,20): error TS1005: ';' expected.
../node_modules/vue/types/jsx.d.ts(39,21): error TS1128: Declaration or statement expected.
../node_modules/vue/types/jsx.d.ts(40,1): error TS1128: Declaration or statement expected.
lerna ERR! npm run build stderr:
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm …
```

Pin Vue to 2.6.x

---

research-app/src/App.vue

While experimenting with a catalog in the research app, I realized that HiPS catalogs from user-loaded WTMLs aren't properly recreated when reloading via a query script. This is because `LoadImageCollectionMessage` is not specified as a prerequisite to `LoadHipsCatalogMessage` in the query script handler. This PR fixes that issue. Since this is purely a deserialization issue, it shouldn't have any effect on existing script URLs.

research-app: Load image collections before HiPS catalogs while handling query script

---

engine/src/index.d.ts
engine/wwtlib/FolderUp.cs

This PR exposes the `FolderUp` class from the engine by making the source C# class be `public`. A TypeScript declaration for this class is also added in the engine's `index.d.ts` file.
The main use case for this at the moment is for doing folder browsing at the Vue level. Although we haven't really used it yet, the `FolderView` component that we've been using for the custom interactives (see e.g. [here](https://github.com/Carifio24/wwt-webgl-engine/blob/embed-jwst-collection/embed/src/FolderView.vue)) has the capability to work exactly like the folder browser in the web client, which requires using `FolderUp` to navigate upwards in the folder hierarchy.

Expose FolderUp class

---

engine/wwtlib/FitsProperties.cs
engine/wwtlib/Layers/LayerManager.cs

Trigger callback even if the main image already has been loaded by the engine For example, when a previously added imageset is added.

Fire AddImageSetLayer callback for re-added imageset

---

research-app/src/App.vue

While using pywwt, I noticed that calling a table layer's `remove()` doesn't remove the layer from the research app UI. This is because the pywwt layer removal happens through a message, and currently the research app message handler only removes a spreadsheet layer from the research app store if it's a HiPS. This PR adds the missing logic.
Note that `this.layer` shouldn't be null if `this.internalId` isn't null (which is the block we're in here), so that check is really a TypeScript thing.

research-app: Remove non-HiPS spreadsheet layers from UI on removal message

---

engine/wwtlib/Util.cs

This PR resolves #54. The tour duration bug described in that issue is due to extra factors of 10 in two constants in the engine's `Util::ParseTimeSpan` static method. This function converts an HH:MM:SS.S time duration to milliseconds. However, the conversion factors for minutes and hours are both 10 times larger than they should be - e.g. there are 60000 milliseconds in one minute, not 600000. The same issue occurs with hours.

Fix bug in time span parsing

---

research-app-messages/src/index.ts
research-app/src/App.vue

This one has been bugging me for a long time, so I decided to finally look into the issue. 
The main problem I have encountered is in jupyter where wwt-jupyterlab I cannot move any windows on top of the WWT app. All mouse events happening on top of WWT never reach jupyter in this case, because WWT is inside an iframe. Since the mouse events cannot go through an iframe for security reasons, we can create a relay with `postMessage`.
This PR let's clients, like wwt-jupyterlab (and other people using the research app in an iframe), know when the drag operation events are occurring inside WWT. Then the client will have to throw a mousemove or mouseup event to get the desired result. Like this: https://github.com/WorldWideTelescope/wwt-jupyterlab/pull/13
Added code:
- Now posting pointermove/up …

Enable drag operations over WWT

---

engine-vuex/src/store.ts
engine-vuex/src/wwtaware.ts
engine/src/index.d.ts
engine/wwtlib/Coordinates.cs
engine/wwtlib/WWTControl.cs

This PR adds functionality to the engine to find the x and y coordinates of the screen point corresponding to a given RA and Dec. The plumbing to expose this to TypeScript is also added.
Basically, this adds three new functions to the engine itself: `TransformWorldPointToPickSpace`, `SphericalSkyToCartesian`, and `GetScreenPointForCoordinates`. These three functions are intended as essentially inverse functions to `TransformPickPointToWorldSpace`, `CartesianToSphericalSky`, and `GetCoordinatesForScreenPoint`, respectively.
I can see a few intended use cases. I have some ideas on how to use this to improve the point selection in the research app, and this could also be used for building dynamic scale bars or anything else distance/size-based.

Add functionality to find screen point for given coordinates

---

engine/wwtlib/Layers/FitsImage.cs

This fixes the issue of half pixel off for untiled FITS. 
Long story short, the issue is that `CRPIX` is referring to the center of the pixel, while `referenceX` is not. 
Does not fix issue with half pixel off for tiled tangential FITS - I'll look into that issue tomorrow.

Corrected half pixel off issue when displaying standalone FITS files

---

package-lock.json
package.json
research-app/src/App.vue

This PR looks to improve the point selection functionality in the research app, primarily by making use of the functionality added to the engine in #206.
The research app determines whether a moving pointer is over a source by getting the RA/Dec of the pixel coordinate of the event, determining the closest source (using great-circle distance), and checking whether the source is "close enough". Currently this "close enough" threshold is determined by a magic constant whose meaning and units are pretty nebulous (and zoom-dependent). This PR replaces the current "close enough" step with the following:
* Use the new engine functionality to find the pixel coordinate of the closest source
* Check whether the pixel distance between the pointer and the closest source is smaller than some …

research-app: Improve point selection

---

engine/wwtlib/Imageset.cs
engine/wwtlib/TangentTile.cs
engine/wwtlib/WWTControl.cs
tests/page_objects/researchApp.ts

This PR has two parts:
1. Zoom position was wrong for both tiled tangential imagesets and untiled images
2. Half pixel correction for tiled tangential imagesets
**Regarding the first issue:**
For untiled images, `GotoRADecZoom` could be called with a RA < 0, which got clamped to 0, resulting in a wrong position. For tiled tangential imagesets the goto destination was off by the `offsetX` and `offsetY` in the wrong directions. Tbh, I did not look into the exact reason because we need to decide the desired behaviour of the goto action. Right now, we have a mix of solutions, where we sometimes try to go to the center of the image and sometimes to the center of the coordinate system like `CRPIX`. The buttons in the research app seem to always go for the coordinate system position, which …

FITS position adjustments

---

package-lock.json
package.json
research-app/src/App.vue

This PR fixes a small bug from the Vue 3 migration. The research app component's `lastSelectedCount` is now turned into a `Proxy`, which causes a `DOMException` when sending the message describing the last selected source (things work fine app-side). The fix here is to use Vue's `isProxy` and `toRaw`, if necessary, to serialize the original non-proxy object.

Ensure that source message doesn't try to send proxy

---

research-app-messages/src/settings.ts
research-app/package.json
research-app/src/App.vue

This PR allows changing how close the pointer needs to be (in pixels) for a source to be considered close enough to select (by default, this is 4 pixels). This is done by adding a `selectionProximity` setting to the research app, which allows this to be changed via a `modify_settings` message. The `distanceThreshold` data field in the research app component has also been renamed to `selectionProximity` for consistency (overall, I felt that "selection proximity" gave a more obvious meaning, but I'm open to other suggestions).

Allow changing selection proximity in research app

---

engine-helpers/src/index.ts
engine-pinia/src/store.ts
engine-pinia/src/wwtaware.ts
engine/src/index.d.ts
engine/wwtlib/WWTControl.cs

This PR adds functionality to the engine to allow obtaining the time necessary for the `GotoRADecZoom` and `GotoTargetFull` motions. This is done via the functions `TimeToRADecZoom` and `TimeToTargetFull`, respectively, along with some refactoring of shared calculations. `TimeToRADecZoom` is also exposed to the Pinia layer - I didn't do this for `TimeToTargetFull` since `GotoTargetFull` isn't exposed.
These implementations are based on the implementations of the corresponding goto functions. A few notes/thoughts:
• I did some testing in the browser, by comparing the reported and actual execution times (nothing fancy - I just surrounded an awaited goto call by `Date.now`s), and agreement is very good - on average, I found the execution time to be about 0.1% more than the reported time.
• …

Expose getting time for some goto movements

---

engine/wwtlib/Layers/SpreadSheetLayer.cs
engine/wwtlib/Layers/VoTableLayer.cs
research-app/src/SpreadsheetItem.vue

This PR modifies spreadsheet and VO table layers to use the correct images when the plot mode is `point` or `square`. Previously these modes were using an incorrect marker.
The reason for this is that, with the exception of the circle, the images for the layer markers come from [here](https://web.wwtassets.org/engine/assets/pins.png). Each sub-image here is 32 pixels square. The appropriate image is accessed via an index, which is zero-indexed and runs through the grid in reading order. This index is converted into a row and column, and then a 32 pixel square starting from the appropriate point is used for the image texture. However, the circle and square cases were using the wrong index, so the wrong image was being used. This PR fixes those indices.
I suppose this is a breaking change, …

Use correct image for point and circle modes

---

engine-helpers/package.json
engine-helpers/src/engine.ts
engine/src/index.d.ts
engine/wwtlib/Constellations.cs
engine/wwtlib/Settings.cs
engine/wwtlib/Tours/ISettings.cs
engine/wwtlib/Tours/TourStop.cs
engine/wwtlib/WWTControl.cs

This PR adds functionality to the engine to allow changing the colors for the various sky overlays that can be drawn, and exposes these new settings to the TypeScript layer. The default values for all of these settings are the values that are currently hard-coded into the engine. This also does the same for the height of the constellation name text. (Note that the function that draws the constellation names also takes a scale parameter, but from my experimentation with different values, the display only depended on the product of these two values).
Note that these color settings don't respect the opacity of the given color. The reason for that is [this line](https://github.com/WorldWideTelescope/wwt-webgl-engine/blob/master/engine/wwtlib/Graphics/Shaders.cs#L101), and similar ones …

Allow modifying overlay colors and constellation name height

---

research-app-messages/src/index.ts
research-app/package.json
research-app/src/App.vue

This PR modifies the research app and `ViewStateMessage` to expose the roll angle in the application state updates. The intended downstream use case is for a client like `glue-wwt` or CosmicDS, which may want to save and restore the state of the WWT view. For consistency with [`CenterOnCoordinatesMessage`](https://github.com/WorldWideTelescope/wwt-webgl-engine/blob/master/research-app-messages/src/classic_pywwt.ts#L115), I decided to expose this number in degrees.

Expose roll angle in `ViewStateMessage`

---

engine/wwtlib/Graphics/Texture.cs
engine/wwtlib/MainView.cs
engine/wwtlib/URLHelpers.cs
engine/wwtlib/WebFile.cs

This PR adds the minimal set of guards necessary to import the engine package in a non-browser context. The intended use case for this is for server-side code that doesn't need the browser APIs. We need these guards because there are a few objects that get instantiated on the module load (e.g. `URLHelpers.singleton`) that call browser APIs.
FWIW, I originally tried using some ScriptSharp functionality (see [this branch](https://github.com/Carifio24/wwt-webgl-engine/tree/ssr-guards-v1)), but that didn't help - it looks like the `typeof` check needs to be in the same scope as the browser API use.

Allow importing engine in non-browser context

---

README.md
ci/azure-main-build.yml
tests/bslocal.conf.ts
tests/config.ts
tests/local.conf.ts
tests/scripts/bslocal.runner.js

While setting up a BrowserStack configuration for the MiniDS repo, I noticed that BrowserStack has seemingly updated the format of the field names in their configurations. We had been using snake_case, but they seem to now want camelCase: see [here](https://www.browserstack.com/docs/automate/selenium/select-browsers-and-devices) (note that Nightwatch uses Selenium). This PR makes those updates. Looking back at our most recent CI logs, it seems that only the default browser environment was running, rather than the several specified in the workflow, which I suspect is related to this. I also fixed a few minor things that my linter was complaining about.

Update BrowserStack configurations

---

engine-helpers/package.json
engine-helpers/src/index.ts
engine-pinia/package.json
engine-pinia/src/store.ts
engine-pinia/src/wwtaware.ts
engine/src/index.d.ts
engine/wwtlib/WWTControl.cs

This PR generalizes the current `CaptureThumbnail` functionality with a new `CaptureFrame` method of the `WWTControl` class. This method captures the current frame of the WWT view, and allows specifying the width, height, and format of the image output. `CaptureThumbnail` now simply calls the more general function. Additionally, this PR exposes this method to the Vue layer via the Pinia store.
Internally, the frame capture uses `toBlob`, which uses a `BlobCallback` to allow manipulation of the created image blob. Since our API is Promise-based, the exposure to the store is done via a Promise that resolves to the blob in the callback.

Generalize and expose capture functionality

---

engine-helpers/package.json
engine-helpers/src/index.ts
engine-pinia/package.json
engine-pinia/src/store.ts
engine-pinia/src/wwtaware.ts
engine/src/index.d.ts
engine/wwtlib/SpaceTimeController.cs
engine/wwtlib/TileCache.cs
engine/wwtlib/VideoOutputType.cs
engine/wwtlib/WWTControl.cs
engine/wwtlib/wwtlib.csproj

This PR is my proposal for adding the "video capture as frames" functionality, which exists in the Windows client, into the web engine. The C# code for handling this is largely stolen from the Windows client implementation, with a few small tweaks to fit this context.
For the sake of completeness, the basic idea is that this adds a notion of being in a "frame dumping" state to the engine. The main change is that this affects how the `SpaceTimeController` updates its current time, which is now controlled by a new `metaNow` member value. If we aren't frame dumping, things update as normal. But if we are, setting this value via the setter is a no-op - to move time forward we need to call `NextFrame`, which increments time by the appropriate amount for the frame dumping FPS. This method is …

Add video capture as frames functionality

---

engine-helpers/src/index.ts
engine/wwtlib/IViewMover.cs
engine/wwtlib/WWTControl.cs

This PR makes some improvements to the video capture functionality introduced in #239. It turns out there was an issue with that implementation where frames could sometimes arrive out of order, which is obviously not good. This PR looks to fix that by adding adding a queue for frames that we aren't yet ready to pass into the stream.
The basic way that this works is that we intercept the `BlobReady` (C# for `BlobCallback`) callback that is passed into `CaptureVideo`, and use it to create a more complicated callback that manages a queue of frames, keyed by frame number. We keep track of which frames have already been "processed" (passed in to the callback) via an index. This method also makes sure to capture the frame number as soon as it's called, in the scope where the callback is …

Video capture, part 2

---

engine/src/index.d.ts

This PR adds a TypeScript declaration for the `SpaceTimeController`'s `get_metaNow` getter, which returns the `metaNow` property that was added in #239. This is useful for Vue-side stuff where we're capturing video frames and need the current time (my current case is for adding tweening to the preview videos).
@pkgw Note that not having this exposed isn't blocking what I'm doing at all  - the function exists in the engine JS, so I can just `ts-ignore` the TypeScript complaints or add the declaration locally for now.

Expose `SpaceTimeController::get_metaNow` to TypeScript

---

research-app/src/App.vue

This PR is to address an issue discovered while trying to run CosmicDS in an environment with restrictive (i.e. HTTPS-only) internet. The issue is that we use an HTTP URL [for the HiPS WTML](https://github.com/WorldWideTelescope/wwt-webgl-engine/blob/master/research-app/src/App.vue#L1196), together with the fact that message handlers aren't properly set up if the collection load [here](https://github.com/WorldWideTelescope/wwt-webgl-engine/blob/master/research-app/src/App.vue#L2858) fails.
This attempts to address the issue by:
* Having the HiPS URL protocol match that of the window - in particular, we'll use an HTTPS URL in an HTTPS context
* Moving the message handler setup into a `finally` block for the HiPS collection load. In the case that load fails, a query script that wants to set …

Update HiPS URL and message handler setup

---

research-app/src/App.vue

This PR solves the same problem as #218, just in a slightly different place. That PR ensured that the last selected source couldn't be sent as a proxy, but we can actually get the same issue when sending the message describing the list of currently selected sources. This is a problem for downstream applications where the app's `statusMessageDestination` is non-null (e.g. pywwt), since the `postMessage` call app-side will fail as the proxy can't be cloned.
This PR refactors the `isProxy`/`toRaw` logic into the `prepareForMessaging` method, which gets called during the dispatch for both message types (and fits logically, as this is necessary to prepare the data for messaging).

Ensure that source list message doesn't try to send proxy

---

engine-helpers/package.json
engine-helpers/src/index.ts
engine-pinia/package.json
engine-pinia/src/store.ts
engine-pinia/src/wwtaware.ts
engine/src/index.d.ts
engine/wwtlib/WWTControl.cs

This method now returns that imageset that actually ended up in the repository. This might be the imageset that the caller wanted to add, or it might be a preexisting one, if there is already an imageset with the same URL in the database. The difference might matter if one wishes to do a name-based lookup of the imageset, since the two equivalent imagesets might have different name fields.

Have the `addImagesetToRepository` method return an imageset

---

engine/wwtlib/WWTControl.cs

This PR adds functionality to the engine that allows for rotating on a touch screen using a two-finger motion. The main ideas behind this are:
* I figured that users likely don't want to both zoom and rotate at the same time, so this implementation only does one on a given two-touch movement. This is done by determining the radial and tangential components of the motion, and only acting on the one whose magnitude is greater.
- The center of rotation/zoom is determined for us: it's the center of the WWT view (rather than being, say, something determined by the motion). Because of this, we compute the radial and tangential components for each touch separately, and then add their magnitudes.
* I personally often like to rotate with one stationary finger "holding" and the other to move. This …

Two-finger touch rotation

---

engine/wwtlib/Annotation.cs

While working on https://github.com/glue-viz/glue-wwt/pull/96, I noticed some issues with changing the opacity of the line, even though we added support for annotation opacity in #238. Since the opacity would update when other properties were changed, I realized that the issue is that we don't mark the annotation batch as dirty when opacity is updated. This means that opacity updates are only realized after another property that _does_ mark the batch as dirty has been changed. This PR remedies this by marking the batch as dirty when the opacity has changed.
Do we also want to do the same thing for the `Label` and `ShowHoverLabel` properties? It seems like we would, but I don't know enough about what these are used for.

Have opacity set annotation batch as dirty

---

engine/wwtlib/WWTControl.cs

In the course of exposing some pywwt stuff to glue-wwt, I noticed that the `crosshairsColor` setting, while exposed downstream, doesn't actually have any effect. The reason for this is that the WebGL crosshair color is hardcoded to white, rather than using the setting value. The HTML5 canvas implementation does use this setting (which I assume is why it had already been exposed to pywwt). This PR updates the code that draws the crosshair to take the setting into account. Note that the `crosshairsColor` setting is stored in the engine as a string, not a `Color`.

Actually use crosshairs color setting

---

docs/engine/engine-pinia-index.md
engine-pinia/src/Component.vue

We've a use case in which multiple instances of the Vue application are being mounted to the same dom (specifically in an ipywidget context with Solara). In this case, however, the id of the div is always the same, causing issues in rendering. This PR allows for passing in a custom id to which the Vue component can be mounted, falling back to the default case of an incremented id when the prop is not provided.

Allow multiple instances to be mounted

---

engine/esm/wwt_control.js

This PR resolves #268 by assigning the alt/az coordinates of the tracked object to the render context's alt/az when in local horizon mode.

Fix local horizon mode tracking

---

docs/engine/content/apiref/_index.md
docs/engine/engine-pinia-index.md
engine-pinia/src/index.ts
engine-pinia/src/shims-vue.d.ts
engine-pinia/src/store.ts
engine-pinia/src/wwtaware.ts
research-app-messages/src/tours.ts

I realized that the Pinia store methods weren't actually getting documented — while docstrings in `wwtaware.ts` worked for properties, they weren't coming through for methods. It is probably better to center the docs on the engineStore anyway, since Vue is pushing people towards the composition API, so here we bite the bullet and shift everything over. It is now looking like the docs are all there.

Yet more docs work

---

engine/esm/coordinates.js
engine/esm/wwt_control.js

This PR resolves #273 by making some changes to the transformations between world and screen coordinates. Note that the `Coordinates` functions that are modified here are only used in the `transformPickPointToWorldSpace` and `transformWorldPointToPickSpace` functions.
The reason that this worked before is because when the roll is zero, the view matrix is almost the identity - that fact combined with the minus sign that had been in the coordinate transformations made things work out okay.
This should be easy to test - open up the research app, load up a HiPS catalog, roll the view, and check that the point selection is still working.

Fix transformations between world and screen coordinates when roll is nonzero

---

engine/esm/url_helpers.js

If we were given a URL like `http://mydomain.com:80/` to rewrite in force-HTTPS mode, we'd change it to `https://mydomain.com:80/`, which obviously isn't going to work.
In that one case, it makes sense to rewrite to `https://mydomain.com/` and see what happens. In cases with non-standard port specifications, that's definitely *not* going to work, so in those cases, we just have to keep the URL as insecure HTTP and hope the browser doesn't ding us.
This change motivated by an issue in `ShowImage.aspx`, which seems to have started including the `:80` in the URLs it emits in its redirects, breaking the Astrometry.Net workflow. I'm not sure why that changed, and we could try to change it back, but this modification here makes the rewriting code more correct, and should fully solve the …

engine/esm/url_helpers.js: fix HTTPS rewriting corner case

---

engine/webpack.config.js

The Webpack default is `self` but as far as I can tell, `this` is preferable:
https://webpack.js.org/configuration/output/#outputglobalobject
https://stackoverflow.com/questions/64639839/typescript-webpack-library-generates-referenceerror-self-is-not-defined
This fixes a problem with testing/running the Constellations frontend with the latest version of the engine.

engine: build the UMD module with a `globalObject` of `this`

---

engine/esm/wwt_control.js

This PR aims to solve some usability issues with the two-touch handling. There are two main changes here:
* If a user has either zoomed or rotated during the current touch sequence, dragging isn't possible until they remove both fingers and start a new touch sequence. This removes the issue that we currently see where it's easy to not pick up both fingers at exactly the same time and get unintended movement after zooming or rotating.
* Allow only one of either zooming or rotating during the same touch sequence. This prevents unintended zooming when rotating, and vice versa. This is a bit more restrictive, so I'm open to other suggestions here. We could always set some sort of timeout (e.g. if you haven't rotated in N milliseconds, unset the rotation flag, and similar for zoom), but I …

Adjust double-touch logic for better usability

---

docs/engine/research-app-messages-index.md
engine-pinia/src/store.ts
engine-pinia/src/wwtaware.ts
engine/esm/index.js
engine/esm/tile_cache.js
engine/src/index.d.ts
research-app-messages/src/index.ts
research-app/src/App.vue

This PR resolves #290 by adding functionality to allow refreshing the tile cache. The engine-level implementation is based on the existing functionality from the Windows client [here](https://github.com/WorldWideTelescope/wwt-windows-client/blob/master/WWTExplorer3d/TileCache.cs#L42). I've retained the `try`-`catch` nature of the cache clearing in case some particular tile type's `cleanUp` can throw. This new functionality is also exposed to the Pinia layers and the research app messaging so that it can be used in downstream clients (e.g. `pywwt`).
Since the tile cache isn't really something that clients should be manipulating directly, the only function that I've exposed to the Pinia layer is this new method here. Obviously this doesn't place any restriction at the engine JS level, …

Allow refreshing tile cache

---

engine/esm/wwt_control.js

The current version does not check the value of zoomMin when zooming, so nothing changes when it gets set. This just duplicates the logic used for the maximum zoom and uses it for the minimum zoom.

keep track of zoomMin

---

ci/azure-deployment.yml
ci/azure-main-build.yml

We're not building binary artifacts, so it's not important to have precise control over the OS version here.
Doing this since the release automation failed with a missing `libssl.so.3` just now.

ci: use ubuntu-latest for all images, rather than fixing 20.04

---

engine/esm/wwt_control.js

This PR provides an implementation of the idea discussed in https://github.com/WorldWideTelescope/wwt-webgl-engine/pull/283#issuecomment-1804981457 and the following comment, where the midpoint of the two touch locations is used as the "center point" for calculations, rather than the viewport center.
As discussed there, this allows zooming and rotating from different areas of the screen, although of course the center of these motions is still the viewport center. The implementation here is simple - when a second touch is reported, we calculate the center of the two touches and save that as `_twoCenterTouch`, then use that in the zoom/rotate calculations. When we go down to < 2 touches, we reset that to `null`.
@pkgw Would be curious to know what you think. With this, I think the only …

Use midpoint of touches for zoom/rotate calculations

---

engine/esm/wwt_control.js

This PR resolves #303. The change here is to use `get_zoomMax()` to find the context-dependent max zoom (including accounting for user-specified zoom bounds). Additionally, I also added some logic to make sure that the zoom is greater than the relevant minimum zoom as well.

Use mode-dependent bounds in gesture handler

---

docs/engine/content/apiref/_index.md
docs/engine/content/freestanding-mode/_index.md

I happened to notice that a few of the documentation links are currently broken because they use a relative path syntax instead of Zola's internal link format, which results in the `.md` file extension not being removed and thus the URL being wrong. This PR fixes those.

Fix a couple of Zola Markdown links

---

ci/azure-main-build.yml
engine-pinia/src/store.ts
engine-pinia/src/wwtaware.ts

While working on our newest WWT-based Cosmic Data Story, I noticed that the Pinia layer currently doesn't expose any way to stop a currently playing tour. This PR looks to remedy that by adding two new methods to the Pinia store; one for stopping a currently playing tour, and another to close the currently active tour player. These largely wrap the tour player methods. `closeTourPlayer` also updates some store-level data regarding the current tour state and sets the `uiController` of the `WWTControl` to be null (which moves the main control back to its default rendering mode).
I noticed that there are existing methods inside of the `WWTControl` to play and pause the current tour, but that our store methods instead use the tour player directly; for consistency I followed the same pattern …

Expose tour-stopping functions to Pinia layer

---

engine-helpers/src/index.ts
engine-pinia/src/store.ts
engine/esm/script_interface.js
engine/esm/view_mover.js
engine/esm/wwt_control.js
engine/src/index.d.ts

This PR implements something that we want in CosmicDS, which is the ability to specify the duration of a movement between two locations.
As for how I implemented this:
* Add a new optional `duration` parameter to our parameters that control goto movements. This represents the desired duration of the move, in seconds.
* We have two view mover classes: `ViewMoverKenBurnsStyle` and `ViewMoverSlew`. The Ken Burns-style mover already has a parameter for the time to target, so almost all of the work here is for the slew mover. We generally create the slew mover via its `create` function (in fact, I think that's the only way that we do in the codebase), so I've updated that function to take in a `duration` parameter. If the caller doesn't pass anything in, this will be undefined, and the …

Allow specifying duration of movement time

---

docs/engine/content/tutorial/add-image/index.md

`zola check` very nicely pointed out to us in CI that http://callbackhell.com is now broken - indeed, it seems that the site is totally down/no longer exists. Thus this PR updates this link to point [here](https://www.geeksforgeeks.org/javascript/what-to-understand-callback-and-callback-hell-in-javascript/), another description of callback hell that isn't broken. If the callbackhell website comes back online at some point, we can always re-point to that instead.

Replace broken link in documentation

---

engine-types/src/index.ts
engine/esm/grids.js
engine/esm/settings.js
engine/esm/wwt_control.js
engine/src/index.d.ts

This PR adds the ability to connect the ecliptic ticks via a circle. This is something that we want for CosmicDS (see our [Planet Parade](https://github.com/cosmicds/planet-parade) story), so I figured that this might as well be made available for WWT users in general.
This is controlled via a new engine setting, `showEclipticCircle`. This is set to false by default, and only has an effect if `showEcliptic` is turned on. This setup ensures backwards compatibility - existing clients won't be adjusting this previously nonexisting setting, so they'll get the standard non-circle ecliptic.

Allow drawing ecliptic circle
